version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"
ports: "80:80;2222:22"

packages: ["php8.3-sqlite3"]
config_file:
  template: "config.php.dist"
  target: "config.php"

command:
  build:
    - "composer update"

  test:
    - "vendor/bin/phpspec run"
