# Use root/example as user/password credentials
version: '3.1'

services:

  devdb:
    image: mysql
    restart: "no"
    environment:
      MYSQL_DATABASE: demo
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_USER: user
      MYSQL_PASSWORD: "test"
    networks:
      - phore-orm
    ports:
      - "3306:3306"


networks:
  phore-orm:
    external: true
